# Generated by Django 4.1.2 on 2023-10-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likeforcomment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='likeforcomment',
            name='target',
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_at'),
        ),
        migrations.DeleteModel(
            name='LikeForArticle',
        ),
        migrations.DeleteModel(
            name='LikeForComment',
        ),
    ]
